# api-server/Chart.yaml

apiVersion: v2
name: api-server
description: A Helm chart for deploying Rust API server with PostgreSQL
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
