primary:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: purpose
              operator: Equal
              values:
                - db # PostgreSQL이 배치될 노드 그룹

  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: 1

replica:
  replicaCount: 1

auth:
  username: pilmo
  password: 1234
  database: database

service:
  type: ClusterIP
